version: "1.1"
name: Status Check
env:
  host: example.com
tests:
  index:
    steps:
      - name: GET request
        http:
          url: http://localhost:3000
          method: GET
          check:
            status: 404
      - name: Get home
        http:
          url: http://localhost:3000/api/index
          method: GET
          check:
            status: 200
